# .readthedocs.yml
# Read the Docs configuration for MkDocs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install -r docs/requirements.txt

# Documentation builder
doc_types:
  mkdocs:
    configuration: mkdocs.yml
    fail_on_warning: false

# Python environment
python:
  install:
    - requirements: docs/requirements.txt

# General settings
language: en
