# .readthedocs.yml
# Read the Docs configuration file for MkDocs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the documentation type to MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Python environment configuration
python:
  version: 3.10
  install:
    - requirements: docs/requirements.txt

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install -r docs/requirements.txt

# General settings
language: en
